function mpprefabgen
% Generate the prefab .mat file for pumpkindesigner.

% Copyright 2024 The MathWorks, Inc.

    PREFABS(1) = gen_prefab('pumpkin',...
                            'Radius', 1,...
                            'Height', .8,...
                            'NumBumps', 10,...
                            'BumpDepth', .1,...
                            'SecondaryBumpDepth', .02,...
                            'DimpleDepth', .2,...
                            'Colors', [ validatecolor('#f06000'); validatecolor('#ff7518') ],...
                            'SpeckleSize', 0,...
                            ... 'SpeckleColorRatio', .5,...
                            ... 'SpeckleTransitionRatio', .2,...
                            'StemRadius', [ .06 .1 ],...
                            'StemDims', [ .4 .5 ],...
                            'StemColor', validatecolor('#008000'));

    PREFABS(2) = gen_prefab('appalachian',...
                            'Radius', 1,...
                            'Height', .8,...
                            'NumBumps', 10,...
                            'BumpDepth', .1,...
                            'SecondaryBumpDepth', 0,...
                            'DimpleDepth', -.2,...
                            'Colors', [ validatecolor('#9a6525'); validatecolor('#e9af66') ],...
                            'SpeckleSize', 0,...
                            ... 'SpeckleColorRatio', .5,...
                            ... 'SpeckleTransitionRatio', .2,...
                            'StemRadius', [ .09 .15 ],...
                            'StemDims', [ .2 .5 ],...
                            'StemColor', validatecolor('#e9af66'));
    PREFABS(3) = gen_prefab('bluedoll',...
                            'Radius', 1,...
                            'Height', .7,...
                            'NumBumps', 9,...
                            'BumpDepth', .06,...
                            'SecondaryBumpDepth', .03,...
                            'DimpleDepth', .3,...
                            'Colors', [ validatecolor('#808c74'); validatecolor('#d8ded2') ],...
                            'SpeckleSize', 0,...
                            ... 'SpeckleColorRatio', .5,...
                            ... 'SpeckleTransitionRatio', .2,...
                            'StemRadius', [ .1 .15 ],...
                            'StemDims', [ .3 .5 ],...
                            'StemColor', validatecolor('#918151'));
    PREFABS(4) = gen_prefab('cinderella',...
                            'Radius', 1.4,...
                            'Height', .9,...
                            'NumBumps', 9,...
                            'BumpDepth', .03,...
                            'SecondaryBumpDepth', .03,...
                            'DimpleDepth', .5,...
                            'Colors', [ validatecolor('#cf4020'); validatecolor('#f5562a') ],...
                            'SpeckleSize', 0,...
                            ... 'SpeckleColorRatio', .5,...
                            ... 'SpeckleTransitionRatio', .2,...
                            'StemRadius', [ .08 .15 ],...
                            'StemDims', [ .2 .8 ],...
                            'StemColor', validatecolor('#006400'));
    PREFABS(5) = gen_prefab('howden',...
                            'Radius', 1,...
                            'Height', 1.2,...
                            'NumBumps', 20,...
                            'BumpDepth', .03,...
                            'SecondaryBumpDepth', .01,...
                            'DimpleDepth', .2,...
                            'Colors', [ validatecolor('#f06000'); validatecolor('#ff7518') ],...
                            'SpeckleSize', 0,...
                            ... 'SpeckleColorRatio', .5,...
                            ... 'SpeckleTransitionRatio', .2,...
                            'StemRadius', [ .11 .15 ],...
                            'StemDims', [ .1 .5 ],...
                            'StemColor', validatecolor('#003d00'));
    PREFABS(6) = gen_prefab('kabocha',...
                            'Radius', .9,...
                            'Height', .7,...
                            'NumBumps', 8,...
                            'BumpDepth', .02,...
                            'SecondaryBumpDepth', .01,...
                            'DimpleDepth', .1,...
                            'Colors', [ validatecolor('#8aa385'); validatecolor('#455856') ],...
                            'SpeckleSize', .005,...
                            ... 'SpeckleColorRatio', .5,...
                            ... 'SpeckleTransitionRatio', .2,...
                            'StemRadius', [ .06 .1 ],...
                            'StemDims', [ .1 .2 ],...
                            'StemColor', validatecolor('#cbc688'));
    PREFABS(7) = gen_prefab('lumina',...
                            'Radius', 1,...
                            'Height', 1,...
                            'NumBumps', 18,...
                            'BumpDepth', .03,...
                            'SecondaryBumpDepth', 0,...
                            'DimpleDepth', .2,...
                            'Colors', [ validatecolor('#dddddd'); validatecolor('#eeeeee') ],...
                            'SpeckleSize', 0,...
                            ... 'SpeckleColorRatio', .5,...
                            ... 'SpeckleTransitionRatio', .2,...
                            'StemRadius', [ .06 .1 ],...
                            'StemDims', [ .2 .2 ],...
                            'StemColor', validatecolor('#003d00'));
    PREFABS(8) = gen_prefab('pumpkemon',...
                            'Radius', 1,...
                            'Height', .7,...
                            'NumBumps', 11,...
                            'BumpDepth', .03,...
                            'SecondaryBumpDepth', .02,...
                            'DimpleDepth', .3,...
                            'Colors', [ validatecolor('#e8aa13'); validatecolor('#ffffbb') ],...
                            'SpeckleSize', .01,...
                            ... 'SpeckleColorRatio', .3,...
                            ... 'SpeckleTransitionRatio', .2,...
                            'StemRadius', [ .06 .1 ],...
                            'StemDims', [ .3 .4 ],...
                            'StemColor', validatecolor('#003d00'));
    PREFABS(9) = gen_prefab('orangita',...
                            'Radius', 1,...
                            'Height', .8,...
                            'NumBumps', 8,...
                            'BumpDepth', .1,...
                            'SecondaryBumpDepth', .05,...
                            'DimpleDepth', .4,...
                            'Colors', [ validatecolor('#d06b00'); validatecolor('#f48f19') ],...
                            'SpeckleSize', 0,...
                            ... 'SpeckleColorRatio', .5,...
                            ... 'SpeckleTransitionRatio', .2,...
                            'StemRadius', [ .08 .15 ],...
                            'StemDims', [ .2 .8 ],...
                            'StemColor', validatecolor('#006400'));
    PREFABS(10) = gen_prefab('rumbo',...
                             'Radius', 1.4,...
                             'Height', .8,...
                             'NumBumps', 8,...
                             'BumpDepth', .1,...
                             'SecondaryBumpDepth', .1,...
                             'DimpleDepth', .4,...
                             'Colors', [ validatecolor('#9a6525'); validatecolor('#e9af66') ],...
                             'SpeckleSize', 0,...
                             ... 'SpeckleColorRatio', .5,...
                             ... 'SpeckleTransitionRatio', .2,...
                             'StemRadius', [ .05 .1 ],...
                             'StemDims', [ .3 .8 ],...
                             'StemColor', validatecolor('#664c28'));
    PREFABS(11) = gen_prefab('scheherazade',...
                             'Radius', .9,...
                             'Height', 1.2,...
                             'NumBumps', 8,...
                             'BumpDepth', .05,...
                             'SecondaryBumpDepth', 0,...
                             'DimpleDepth', .1,...
                             'Colors', [ validatecolor('#e8aa23'); validatecolor('#546338') ],...
                             'SpeckleSize', .02,...
                             ... 'SpeckleColorRatio', .2,...
                             ... 'SpeckleTransitionRatio', .2,...
                             'StemRadius', [ .06 .1 ],...
                             'StemDims', [ .1 .2 ],...
                             'StemColor', validatecolor('#6c541e'));
    PREFABS(12) = gen_prefab('snackjack',...
                             'Radius', 1,...
                             'Height', 1,...
                             'NumBumps', 10,...
                             'BumpDepth', .03,...
                             'SecondaryBumpDepth', .02,...
                             'DimpleDepth', .2,...
                             'Colors', [ validatecolor('#f06000'); validatecolor('#ff7518') ],...
                             'SpeckleSize', 0,...
                             ... 'SpeckleColorRatio', .5,...
                             ... 'SpeckleTransitionRatio', .2,...
                             'StemRadius', [ .06 .1 ],...
                             'StemDims', [ .1 .2 ],...
                             'StemColor', validatecolor('#a67b5b'));
    PREFABS(13) = gen_prefab('sweetlightning',...
                             'Radius', 1,...
                             'Height', .8,...
                             'NumBumps', 10,...
                             'BumpDepth', .1,...
                             'SecondaryBumpDepth', .03,...
                             'DimpleDepth', .4,...
                             'Colors', [ validatecolor('#ff7518'); validatecolor('#ffffbb') ],...
                             'SpeckleSize', .08,...
                             ... 'SpeckleColorRatio', .4,...
                             ... 'SpeckleTransitionRatio', .2,...
                             'StemRadius', [ .06 .1 ],...
                             'StemDims', [ .2 .5 ],...
                             'StemColor', validatecolor('#6c541e'));


    save('metapumpkinprefabs.mat','PREFABS');

end

function [PF] = gen_prefab(name, opts)
% Accept all the various inputs of metapumpkin, and create
% a prefab structure from those inputs.

    arguments
        name
        opts.Radius = 1 % diameter of pumpkin
        opts.Height = 1 % height of pumpkin
        opts.Resolution = 200 % density of pumpkin mesh.
        opts.NumBumps = 10 % number of ridges
        opts.BumpDepth = .1 % depth of bumps
        opts.SecondaryBumpDepth = .02 % include secondary bumps of this depth
        opts.DimpleDepth = .2 % depth of dimple under the stem

        opts.SpeckleSize = 0
        %opts.SpeckleColorRatio = .5
        %opts.SpeckleTransitionRatio = .1

        opts.Colors = validatecolor({'#f06000' '#ff7518'},'multiple');
        
        opts.StemStyle = 'Complex'
        opts.StemRadius = [ .06 .1 ]
        opts.StemDims = [ .4 .5 ]
        opts.StemColor = validatecolor('#008000')
    end

    PF.name = name;
    PF.metapumpkin = { "Height"
                       opts.Height
                       "NumBumps"
                       opts.NumBumps
                       "BumpDepth"
                       opts.BumpDepth
                       "SecondaryBumpDepth"
                       opts.SecondaryBumpDepth
                       "DimpleDepth"
                       opts.DimpleDepth
                       "StemStyle"
                       opts.StemStyle
                       "StemRadius"
                       opts.StemRadius
                       "StemDims"
                       opts.StemDims
                       "StemColor"
                       opts.StemColor
                       "SpeckleSize"
                       opts.SpeckleSize
                     };

    if ischar(opts.Colors) || isstring(opts.Colors)
        PF.colormap = opts.Colormap;
        PF.colors = feval(PF.colormap,256);
    else
        PF.colormap = 'custom';
        PF.colors = opts.Colors;
    end
    
end
